### ISSUE TITLE
FID score 90.30, rather than 63.31 ± 0.05 in the paper.

### ISSUE THREAD

**Issue by fikry102** [arnabkmondal/GenDA#4]
“python -m pytorch_fid ../real_babies/ msmt_exp_samples/babies/”

Under the folder "msmt_exp_samples/babies/”, there are a lot of images, such as "generated_499_9.png", "generated_500_0.png", ..., "generated_500_9.png".
 
Which images are used to calculate FID?
Should I delete those images whose name are not prefixed with "generated_500"?

**Comment by arnabkmondal** [comment]
I will rerun and see if there is any issue with the uploaded code. Meanwhile you may use the ```w```s generated using my previous run. [Download Link](https://www.dropbox.com/scl/fi/ipqc29k6zw1srrfoh8bvk/msmt_exp_w.zip?rlkey=em4qysknj889c5vcbyairrvzo&dl=0).  I have added the code for generation from saved ```w```s. [Code Link](https://github.com/arnabkmondal/GenDA/blob/main/few_shot_expts/generate_from_w.py).

**Comment by YuCao16** [comment]
@arnabkmondal Any update about this? I got similar result with your provided `w`s.

**Comment by arnabkmondal** [comment]
@YuCao16 I had retrained and could reproduce the results in the paper. Are you using the same version of python libraries as provided in the [requirements.yml](https://github.com/arnabkmondal/GenDA/blob/main/requirements.yml)?

**Comment by YuCao16** [comment]
> @YuCao16 I had retrained and could reproduce the results in the paper. Are you using the same version of python libraries as provided in the [requirements.yml](https://github.com/arnabkmondal/GenDA/blob/main/requirements.yml)?

@arnabkmondal Thanks for your reply.
I didn't retrain it, I used the generated `w`s you provided in your reply to @fikry102, and what I've done is:
1. Run `python generated_from_w.py`, then I got 1000 generated images in `./gen_imgs`
2. Calculate Fid `python -m pytorch_fid ../images/ ./gen_imgs`
3. I run twice, and got 89,98 and 90.38.
Is there anything I did wrong?

And I have check the requirements is satisfied.

**Comment by arnabkmondal** [comment]
@YuCao16 in step 1 number of generated images should be approximately 5k. Also check the resolution of the real images. It should be 256x256. I am assuming your ../images/ folder contain only the images from the babies and contain all the images from [this link](https://drive.google.com/file/d/1JmjKBq_wylJmpCQ2OWNMy211NFJhHHID/view?usp=sharing). However, note that the images downloaded are of 1024x1024 resolution. You have to resize those images to 256x256.

**Comment by YuCao16** [comment]
> @YuCao16 in step 1 number of generated images should be approximately 5k. Also check the resolution of the real images. It should be 256x256. I am assuming your ../images/ folder contain only the images from the babies and contain all the images from [this link](https://drive.google.com/file/d/1JmjKBq_wylJmpCQ2OWNMy211NFJhHHID/view?usp=sharing). However, note that the images downloaded are of 1024x1024 resolution. You have to resize those images to 256x256.

Thanks for your reply, and that makes sense.
