### ISSUE TITLE
other target domain datasets

### ISSUE THREAD

**Issue by fikry102** [arnabkmondal/GenDA#5]
Could you please provide the download link for other target domain datasets?

**Comment by arnabkmondal** [comment]
Sunglasses [download link](https://drive.google.com/file/d/1Uu5y_y8Rjxbj2VEzvT3aBHyn4pltFgyX/view).
Sketches [download link](https://drive.google.com/file/d/1vgsB7ji-cLVzRhx43DvNSDgV5Up3jFJ2/view).
Artistic faces dataset [download link](https://faculty.runi.ac.il/arik/site/foa/artistic-faces-dataset.asp).
Vangogh houses dataset [download link](https://drive.google.com/file/d/1k5x76NvJRFd-XDSoZTDRtL_IdWD8_VKK/view).
Haunted houses dataset [download link](https://drive.google.com/file/d/1dbW-HTDT82t0ORkA0vlHcOX6dCyccqgu/view).
Wrecked cars dataset [download link](https://drive.google.com/file/d/1IBv1cwPaCFDUDvn9fo8KoCSaZ3s6bsFX/view).
